### ISSUE TITLE
Feature request: default environment config merging

### ISSUE THREAD

**Issue by moltar** [tommy351/kosko#18]
It would be great to be able to define a default environment config, which then would be merged with the environment specific config to override the defaults.

The benefit would be that if a certain environment could be satisfied with defaults, then don't need to create a copy of the environment config file with duplicate data.

Thanks!

**Comment by mefcorvi** [comment]
@tommy351 Do you need a hand with this? It's the only issue that has left in the 0.9 milestone :-)

**Comment by tommy351** [comment]
I created a new pull request #36. Please let me know if you feel something need to be changed.
