### ISSUE TITLE
Feature request: ability to override environment config using CLI arguments

### ISSUE THREAD

**Issue by mefcorvi** [tommy351/kosko#31]
As a DevOps I want to set configuration values during CI/CD process using the command line. For example, in Helm I can use these arguments
```
--set stringArray          Set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
--set-file stringArray     Set values from respective files specified via the command line (can specify multiple or separate values with commas: key1=path1,key2=path2)
--set-string stringArray   Set STRING values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
```
I think that supporting three arguments is too much but it would be great to have at least `--set`.

**Comment by mefcorvi** [comment]
Link to the format used in Helm:
https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set

For the sake of simplicity I suggest the following format: `--set <key> <value>` where the key is a JSONPath. Prefix `$.` will be added automatically to the key. The value is a valid JSON, or if the value can't be parsed from JSON then it should be treated as a plain string. One key/value pair is set with one `--set` argument, multiple pairs are set with multiple arguments.

Examples:
```shell
# multiple arguments, 3307 is forced to be string here
kosko --set image.name mysql --set image.tag 1.3.4 --set mysql.port '"3307"' 

# override entire array
kosko --set imagePullSecrets '[ { "name": "mySecret" } ]' 

# set name of the first item in the array
kosko --set imagePullSecrets[0].name mySecret 

# change all ports recursivelly, JSONPath is $..port
kosko --set .port 80 

# escape characters
kosko --set description "It's a wonderful \"service\" -- or not" 

# disable deployment of the database, false is a boolean
kosko --set mysql.enabled "false"

# sets myService to "true", quotes are escaped
kosko --set myService \'true\'
```

**Comment by mefcorvi** [comment]
@tommy351 I can try to make a PR if you're ok with the proposed format.

**Comment by tommy351** [comment]
This looks good to me. You can start from the `generate` command in `cli` package if you want to make a PR.

**Comment by mefcorvi** [comment]
I missed a case when a user wants to override a component's value.
I mean that currently component values are built from component env values merged with the global env values. Using the proposed `--set` argument it will be possible to override a global value but I believe that should be a way to override a component's env value.

In the Helm chart, env values for the sub-charts are defined in the value file. That makes possible overriding sub-chart values via CLI just as a common nested prop.

If we could have the possibility to define component's values in the main env file, something like this:
```typescript
// staging.ts:
export default {
  someGlobalVar: 1,
  "components/api": { // or probably just "/api"
    someApiVar: 1,
  }
}
```
then it would cover this use case, and it'll be possible to just `--set components/api.someApiVar 2`. Or we can omit the `components` part, so it would be `--set /api.someApiVar 2`. Looks a little bit weird though.

@tommy351 what do you think?

**Comment by tommy351** [comment]
yargs can handle [nested objects](https://github.com/yargs/yargs/blob/master/docs/tricks.md#objects). I think we can use it instead of change the current behavior.

```sh
# Global environment
--set foo=bar

# Component environment
--set.mysql port=3307
```

**Comment by mefcorvi** [comment]
You're right. So it will be:
```
# multiple arguments, 3307 is forced to be string here
kosko --set image.name=mysql --set image.tag=1.3.4 --set mysql.port='"3307"' 

# override entire array
kosko --set imagePullSecrets='[ { "name": "mySecret" } ]' 

# set name of the first item in the array
kosko --set imagePullSecrets[0].name=mySecret 

# change all ports recursivelly, JSONPath is $..port
kosko --set .port=80 

# escape characters
kosko --set description="It's a wonderful \"service\" -- or not" 

# disable deployment of the database, false is a boolean
kosko --set mysql.enabled="false"

# set myService to string "true", quotes are escaped
kosko --set myService=\'true\'

# override mysql port only for "backend" component
kosko --set.backend mysql.port=3307
```

**Comment by mefcorvi** [comment]
@tommy351 Could you advice a way to apply these values from CLI? I see that actual merge is done in  `env` so I suppose that I need to add public property to the `Environment` and set it in the `GenerateHandler`? I don't like this but I don't see an alternative way.

**Comment by tommy351** [comment]
You are right. You probably need to add some methods to the `Environment` class like below:

```ts
class Environment {
  public setAdditionalGlobal(data: any) {}
  public setAdditionalComponent(component: string, data: any) {}
}
```
