### ISSUE TITLE
Feature request : generate without FS

### ISSUE THREAD

**Issue by revolunet** [tommy351/kosko#59]
Hi, do you know is its possible to use `@kosko/generate` without CLI, like... in a browser ?

Something like `generate(components, env);` that could "dump" all the manifests

thanks

**Comment by tommy351** [comment]
It's not possible currently. To do that we need to set a fake fs for [fast-glob](https://github.com/mrmlnc/fast-glob#fs) and a `require` polyfill for `@kosko/require`.

**Comment by revolunet** [comment]
Shouldn't we have an alternative `generate` method for non-FS declarations instead of patching kosko/generate ?

I'm wondering because i'd like to create a little online kosko editor with [this naive viewer](https://github.com/SocialGouv/react-k8s-viewer/)

**Comment by tommy351** [comment]
I am doing some experiments right now. It is easy to replace fs with [memfs](https://www.npmjs.com/package/memfs). But the content from memfs can't be loaded with `require` directly. Have to find a way to load scripts in non-Node environments.

BTW, the viewer looks awesome! 👍

**Comment by revolunet** [comment]
thanks! the viewer is an experiment to better understand kube and improve my TS skills. it should be full-TS at some point.
As i have some hard time explaining kosko powers, this could make it more graphic :)

**Comment by tommy351** [comment]
I added the information about the browser support to the website. Feel free to ask me if you have any questions.

https://kosko.dev/docs/using-in-browser
